name: e_learning_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.3.1
  http: ^0.13.4
  equatable: ^2.0.3
  get_it: ^7.2.0
  dartz: ^0.10.1
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.3
  intl: ^0.17.0
  google_fonts: ^3.0.1
  connectivity_plus: ^3.0.2
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3
  cached_network_image: ^3.2.0
  flutter_launcher_icons: ^0.10.0
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.4
  loading_animation_widget: ^1.2.0+3
  go_router: ^5.1.5
  form_field_validator: ^1.1.0
  badges: ^2.0.3
  persistent_bottom_nav_bar: ^5.0.2
  injectable: ^1.5.3
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  flutter_blurhash: ^0.7.0
  random_date: ^0.0.7
  coupon_uikit: ^0.1.0
  flutter_native_splash: ^2.2.12
  tab_indicator_styler: ^2.0.0
  percent_indicator: ^4.2.2
  timeago: ^3.3.0
  chewie: ^1.3.5
  video_player: ^2.4.7
  animations: ^2.0.7
  youtube_explode_dart: ^1.12.3
  flutter_markdown: ^0.6.13
  modal_bottom_sheet: ^2.1.2
  syncfusion_flutter_barcodes: ^20.3.57
  flutter_rating_bar: ^4.0.1
  image_picker: ^0.8.6
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  image: ^3.2.2
  blurhash_dart: ^1.1.0
  fx_stepper: ^0.0.1
  status_change: ^2.0.0
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  get_it_mixin: ^3.1.4+2
  flutter_inappwebview: ^5.7.2+3
  permission_handler: ^10.2.0
  socket_io_client: ^2.0.0
  safe_device: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  build_runner:
  mobx_codegen: ^2.0.7
  injectable_generator: ^1.5.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/md/
    - .env
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
